name: run main.py

on:
  schedule:
    - cron: '*/5 * * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed


      - name: install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          ffmpeg \
          vim \
          && sudo apt-get clean

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Python Script
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: python main.py
          